### ISSUE TITLE
Add continuous integration?

### ISSUE THREAD

**Issue by richelbilderbeek** [cevo-public/TreePrior-ClockRate#1]
I enjoy the article and intend to experiment with some analysis. In the process, I will add the Travis Continuous Integration service (free for FLOSS development, and blends in with GitHubs smootly) on my fork. Would you be open to Pull Requests adding continuous integration?

If yes, @cevo-public will need to go to [https://travis-ci.org/](https://travis-ci.org/), create a free account (easy, uses data from the GitHub account), and activate the repository (easy as well).

Keep up the good work :+1:

**Comment by laduplessis** [comment]
Hi Richel, thanks for the interest!  I don't really see an advantage to using Travis CI with this project. There are only some scripts for setting up simulations (at the moment hardcoded to submit simulations to the ETH grid) and for plotting figures. Having Travis redo all of the simulations at every push seems like a waste of resources to me. Feel free to add Travis CI to your fork and build on the project!

**Comment by richelbilderbeek** [comment]
The idea is to let another party redo your analysis, to be sure your research is reproducible [1]. At this moment, I can only *trust* I can redo the analysis. Would you add Travis I *know* at least some entity can redo the analysis.

## References

[1] Stodden, Victoria, Friedrich Leisch, and Roger D. Peng, eds. Implementing reproducible research. CRC Press, 2014.

**Comment by tanja819** [comment]
I very much agree with you that research must be reproducible. As mentioned above, ALL scripts are available to redo the analysis, ie. you do not have to _trust_ us, but you can easily _redo_ the analysis.  As mentioned above, feel free to add Travis to your fork!

**Comment by richelbilderbeek** [comment]
Nah, I am not going to waste my time on a Fork. Our colleagues will go this GitHub and will not check the Forks. I will look for other work to build on instead. Feel free to close this Issue.
